# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# test-project foe example

name: Maven Package

on: 
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: maven-built-jar
        path: target/*.jar
